### ISSUE TITLE
UnhandledPromiseRejectionWarning when docker run

### ISSUE THREAD

**Issue by SEKIRO-J** [rayvin-flow/flow-scanner#1]
Hi there,
I'm trying to build my local image,  `docker build -t flow-scanner .`
and i can spin up the container using `docker-compose -f docker-compose.yml up`
my docker-compose.yml file: 
```
version: '3.7'

services:
  flow-scanner:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: flow-scanner

```

I couldn't get the container up and running by using `docker run`,
I tried with both local image and image in docker hub:
```
docker run --env-file=.env rayvinflow/flow-scanner:1.x
```
```
docker run --env-file=.env flow-scanner
```

both give me the following error:

```
% docker run -it  --env-file=.env  flow-scanner:latest 
(node:1) UnhandledPromiseRejectionWarning: Error: Response closed without headers
    at Object.onEnd (/home/node/app/node_modules/@onflow/sdk/dist/sdk.js:1:10252)
    at /home/node/app/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:24233
    at /home/node/app/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11490
    at Array.forEach (<anonymous>)
    at e.rawOnError (/home/node/app/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11452)
    at e.onTransportEnd (/home/node/app/node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:10318)
    at ClientRequest.<anonymous> (/home/node/app/node_modules/@improbable-eng/grpc-web-node-http-transport/lib/index.js:64:27)
    at ClientRequest.emit (events.js:314:20)
    at ClientRequest.EventEmitter.emit (domain.js:483:12)
    at Socket.socketErrorListener (_http_client.js:427:9)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Do you know what could be the root cause? Thank you!

**Comment by SEKIRO-J** [comment]
solved by removing quotes on urls
